INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador A', 'I7 16GB SSD1T', 5403);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador B', 'I7 16GB SSD2T', 6403);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador C', 'I7 16GB SSD2T', 1234);
INSERT INTO TBL_CLIENT (CLIENT_NAME, AGE, CLIENT_EMAIL, CLIENT_PHONE) VALUES ('Glauco Todesco', 44, 'glaucotodesco@gmail.com', '11940028922');
INSERT INTO TBL_CLIENT (CLIENT_NAME, AGE, CLIENT_EMAIL, CLIENT_PHONE) VALUES ('Cainã Antunes', 32, 'cainaantunes@gmail.com', '11940028923');
INSERT INTO TBL_CLIENT (CLIENT_NAME, AGE, CLIENT_EMAIL, CLIENT_PHONE) VALUES ('André Cassulino', 38, 'andrecassulino@gmail.com', '11940028924');
